// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: room.proto

package org.alayse.marsserver.proto.game;

public final class Room {
  private Room() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface RoomRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:org.alayse.marsserver.proto.game.RoomRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required string room = 1;</code>
     */
    boolean hasRoom();
    /**
     * <code>required string room = 1;</code>
     */
    java.lang.String getRoom();
    /**
     * <code>required string room = 1;</code>
     */
    com.google.protobuf.ByteString
        getRoomBytes();
  }
  /**
   * Protobuf type {@code org.alayse.marsserver.proto.game.RoomRequest}
   */
  public static final class RoomRequest extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:org.alayse.marsserver.proto.game.RoomRequest)
      RoomRequestOrBuilder {
    // Use RoomRequest.newBuilder() to construct.
    private RoomRequest(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private RoomRequest(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final RoomRequest defaultInstance;
    public static RoomRequest getDefaultInstance() {
      return defaultInstance;
    }

    public RoomRequest getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private RoomRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              room_ = bs;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.alayse.marsserver.proto.game.Room.internal_static_org_alayse_marsserver_proto_game_RoomRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.alayse.marsserver.proto.game.Room.internal_static_org_alayse_marsserver_proto_game_RoomRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.alayse.marsserver.proto.game.Room.RoomRequest.class, org.alayse.marsserver.proto.game.Room.RoomRequest.Builder.class);
    }

    public static com.google.protobuf.Parser<RoomRequest> PARSER =
        new com.google.protobuf.AbstractParser<RoomRequest>() {
      public RoomRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new RoomRequest(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<RoomRequest> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int ROOM_FIELD_NUMBER = 1;
    private java.lang.Object room_;
    /**
     * <code>required string room = 1;</code>
     */
    public boolean hasRoom() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string room = 1;</code>
     */
    public java.lang.String getRoom() {
      java.lang.Object ref = room_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          room_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string room = 1;</code>
     */
    public com.google.protobuf.ByteString
        getRoomBytes() {
      java.lang.Object ref = room_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        room_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      room_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasRoom()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getRoomBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getRoomBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static org.alayse.marsserver.proto.game.Room.RoomRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.alayse.marsserver.proto.game.Room.RoomRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.alayse.marsserver.proto.game.Room.RoomRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.alayse.marsserver.proto.game.Room.RoomRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.alayse.marsserver.proto.game.Room.RoomRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.alayse.marsserver.proto.game.Room.RoomRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static org.alayse.marsserver.proto.game.Room.RoomRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static org.alayse.marsserver.proto.game.Room.RoomRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static org.alayse.marsserver.proto.game.Room.RoomRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.alayse.marsserver.proto.game.Room.RoomRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(org.alayse.marsserver.proto.game.Room.RoomRequest prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code org.alayse.marsserver.proto.game.RoomRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:org.alayse.marsserver.proto.game.RoomRequest)
        org.alayse.marsserver.proto.game.Room.RoomRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.alayse.marsserver.proto.game.Room.internal_static_org_alayse_marsserver_proto_game_RoomRequest_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.alayse.marsserver.proto.game.Room.internal_static_org_alayse_marsserver_proto_game_RoomRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.alayse.marsserver.proto.game.Room.RoomRequest.class, org.alayse.marsserver.proto.game.Room.RoomRequest.Builder.class);
      }

      // Construct using org.alayse.marsserver.proto.game.Room.RoomRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        room_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.alayse.marsserver.proto.game.Room.internal_static_org_alayse_marsserver_proto_game_RoomRequest_descriptor;
      }

      public org.alayse.marsserver.proto.game.Room.RoomRequest getDefaultInstanceForType() {
        return org.alayse.marsserver.proto.game.Room.RoomRequest.getDefaultInstance();
      }

      public org.alayse.marsserver.proto.game.Room.RoomRequest build() {
        org.alayse.marsserver.proto.game.Room.RoomRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public org.alayse.marsserver.proto.game.Room.RoomRequest buildPartial() {
        org.alayse.marsserver.proto.game.Room.RoomRequest result = new org.alayse.marsserver.proto.game.Room.RoomRequest(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.room_ = room_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.alayse.marsserver.proto.game.Room.RoomRequest) {
          return mergeFrom((org.alayse.marsserver.proto.game.Room.RoomRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.alayse.marsserver.proto.game.Room.RoomRequest other) {
        if (other == org.alayse.marsserver.proto.game.Room.RoomRequest.getDefaultInstance()) return this;
        if (other.hasRoom()) {
          bitField0_ |= 0x00000001;
          room_ = other.room_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasRoom()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.alayse.marsserver.proto.game.Room.RoomRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.alayse.marsserver.proto.game.Room.RoomRequest) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object room_ = "";
      /**
       * <code>required string room = 1;</code>
       */
      public boolean hasRoom() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string room = 1;</code>
       */
      public java.lang.String getRoom() {
        java.lang.Object ref = room_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            room_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string room = 1;</code>
       */
      public com.google.protobuf.ByteString
          getRoomBytes() {
        java.lang.Object ref = room_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          room_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string room = 1;</code>
       */
      public Builder setRoom(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        room_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string room = 1;</code>
       */
      public Builder clearRoom() {
        bitField0_ = (bitField0_ & ~0x00000001);
        room_ = getDefaultInstance().getRoom();
        onChanged();
        return this;
      }
      /**
       * <code>required string room = 1;</code>
       */
      public Builder setRoomBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        room_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:org.alayse.marsserver.proto.game.RoomRequest)
    }

    static {
      defaultInstance = new RoomRequest(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:org.alayse.marsserver.proto.game.RoomRequest)
  }

  public interface RoomResponseProxyOrBuilder extends
      // @@protoc_insertion_point(interface_extends:org.alayse.marsserver.proto.game.RoomResponseProxy)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required string content = 1;</code>
     */
    boolean hasContent();
    /**
     * <code>required string content = 1;</code>
     */
    java.lang.String getContent();
    /**
     * <code>required string content = 1;</code>
     */
    com.google.protobuf.ByteString
        getContentBytes();

    /**
     * <code>required string nextplayer = 2;</code>
     */
    boolean hasNextplayer();
    /**
     * <code>required string nextplayer = 2;</code>
     */
    java.lang.String getNextplayer();
    /**
     * <code>required string nextplayer = 2;</code>
     */
    com.google.protobuf.ByteString
        getNextplayerBytes();

    /**
     * <code>repeated string receiver = 3;</code>
     */
    com.google.protobuf.ProtocolStringList
        getReceiverList();
    /**
     * <code>repeated string receiver = 3;</code>
     */
    int getReceiverCount();
    /**
     * <code>repeated string receiver = 3;</code>
     */
    java.lang.String getReceiver(int index);
    /**
     * <code>repeated string receiver = 3;</code>
     */
    com.google.protobuf.ByteString
        getReceiverBytes(int index);
  }
  /**
   * Protobuf type {@code org.alayse.marsserver.proto.game.RoomResponseProxy}
   */
  public static final class RoomResponseProxy extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:org.alayse.marsserver.proto.game.RoomResponseProxy)
      RoomResponseProxyOrBuilder {
    // Use RoomResponseProxy.newBuilder() to construct.
    private RoomResponseProxy(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private RoomResponseProxy(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final RoomResponseProxy defaultInstance;
    public static RoomResponseProxy getDefaultInstance() {
      return defaultInstance;
    }

    public RoomResponseProxy getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private RoomResponseProxy(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              content_ = bs;
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              nextplayer_ = bs;
              break;
            }
            case 26: {
              com.google.protobuf.ByteString bs = input.readBytes();
              if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
                receiver_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000004;
              }
              receiver_.add(bs);
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
          receiver_ = receiver_.getUnmodifiableView();
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.alayse.marsserver.proto.game.Room.internal_static_org_alayse_marsserver_proto_game_RoomResponseProxy_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.alayse.marsserver.proto.game.Room.internal_static_org_alayse_marsserver_proto_game_RoomResponseProxy_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.alayse.marsserver.proto.game.Room.RoomResponseProxy.class, org.alayse.marsserver.proto.game.Room.RoomResponseProxy.Builder.class);
    }

    public static com.google.protobuf.Parser<RoomResponseProxy> PARSER =
        new com.google.protobuf.AbstractParser<RoomResponseProxy>() {
      public RoomResponseProxy parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new RoomResponseProxy(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<RoomResponseProxy> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int CONTENT_FIELD_NUMBER = 1;
    private java.lang.Object content_;
    /**
     * <code>required string content = 1;</code>
     */
    public boolean hasContent() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string content = 1;</code>
     */
    public java.lang.String getContent() {
      java.lang.Object ref = content_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          content_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string content = 1;</code>
     */
    public com.google.protobuf.ByteString
        getContentBytes() {
      java.lang.Object ref = content_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        content_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int NEXTPLAYER_FIELD_NUMBER = 2;
    private java.lang.Object nextplayer_;
    /**
     * <code>required string nextplayer = 2;</code>
     */
    public boolean hasNextplayer() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string nextplayer = 2;</code>
     */
    public java.lang.String getNextplayer() {
      java.lang.Object ref = nextplayer_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          nextplayer_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string nextplayer = 2;</code>
     */
    public com.google.protobuf.ByteString
        getNextplayerBytes() {
      java.lang.Object ref = nextplayer_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        nextplayer_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int RECEIVER_FIELD_NUMBER = 3;
    private com.google.protobuf.LazyStringList receiver_;
    /**
     * <code>repeated string receiver = 3;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getReceiverList() {
      return receiver_;
    }
    /**
     * <code>repeated string receiver = 3;</code>
     */
    public int getReceiverCount() {
      return receiver_.size();
    }
    /**
     * <code>repeated string receiver = 3;</code>
     */
    public java.lang.String getReceiver(int index) {
      return receiver_.get(index);
    }
    /**
     * <code>repeated string receiver = 3;</code>
     */
    public com.google.protobuf.ByteString
        getReceiverBytes(int index) {
      return receiver_.getByteString(index);
    }

    private void initFields() {
      content_ = "";
      nextplayer_ = "";
      receiver_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasContent()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasNextplayer()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getContentBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getNextplayerBytes());
      }
      for (int i = 0; i < receiver_.size(); i++) {
        output.writeBytes(3, receiver_.getByteString(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getContentBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getNextplayerBytes());
      }
      {
        int dataSize = 0;
        for (int i = 0; i < receiver_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeBytesSizeNoTag(receiver_.getByteString(i));
        }
        size += dataSize;
        size += 1 * getReceiverList().size();
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static org.alayse.marsserver.proto.game.Room.RoomResponseProxy parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.alayse.marsserver.proto.game.Room.RoomResponseProxy parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.alayse.marsserver.proto.game.Room.RoomResponseProxy parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.alayse.marsserver.proto.game.Room.RoomResponseProxy parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.alayse.marsserver.proto.game.Room.RoomResponseProxy parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.alayse.marsserver.proto.game.Room.RoomResponseProxy parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static org.alayse.marsserver.proto.game.Room.RoomResponseProxy parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static org.alayse.marsserver.proto.game.Room.RoomResponseProxy parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static org.alayse.marsserver.proto.game.Room.RoomResponseProxy parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.alayse.marsserver.proto.game.Room.RoomResponseProxy parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(org.alayse.marsserver.proto.game.Room.RoomResponseProxy prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code org.alayse.marsserver.proto.game.RoomResponseProxy}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:org.alayse.marsserver.proto.game.RoomResponseProxy)
        org.alayse.marsserver.proto.game.Room.RoomResponseProxyOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.alayse.marsserver.proto.game.Room.internal_static_org_alayse_marsserver_proto_game_RoomResponseProxy_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.alayse.marsserver.proto.game.Room.internal_static_org_alayse_marsserver_proto_game_RoomResponseProxy_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.alayse.marsserver.proto.game.Room.RoomResponseProxy.class, org.alayse.marsserver.proto.game.Room.RoomResponseProxy.Builder.class);
      }

      // Construct using org.alayse.marsserver.proto.game.Room.RoomResponseProxy.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        content_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        nextplayer_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        receiver_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.alayse.marsserver.proto.game.Room.internal_static_org_alayse_marsserver_proto_game_RoomResponseProxy_descriptor;
      }

      public org.alayse.marsserver.proto.game.Room.RoomResponseProxy getDefaultInstanceForType() {
        return org.alayse.marsserver.proto.game.Room.RoomResponseProxy.getDefaultInstance();
      }

      public org.alayse.marsserver.proto.game.Room.RoomResponseProxy build() {
        org.alayse.marsserver.proto.game.Room.RoomResponseProxy result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public org.alayse.marsserver.proto.game.Room.RoomResponseProxy buildPartial() {
        org.alayse.marsserver.proto.game.Room.RoomResponseProxy result = new org.alayse.marsserver.proto.game.Room.RoomResponseProxy(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.content_ = content_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.nextplayer_ = nextplayer_;
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          receiver_ = receiver_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000004);
        }
        result.receiver_ = receiver_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.alayse.marsserver.proto.game.Room.RoomResponseProxy) {
          return mergeFrom((org.alayse.marsserver.proto.game.Room.RoomResponseProxy)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.alayse.marsserver.proto.game.Room.RoomResponseProxy other) {
        if (other == org.alayse.marsserver.proto.game.Room.RoomResponseProxy.getDefaultInstance()) return this;
        if (other.hasContent()) {
          bitField0_ |= 0x00000001;
          content_ = other.content_;
          onChanged();
        }
        if (other.hasNextplayer()) {
          bitField0_ |= 0x00000002;
          nextplayer_ = other.nextplayer_;
          onChanged();
        }
        if (!other.receiver_.isEmpty()) {
          if (receiver_.isEmpty()) {
            receiver_ = other.receiver_;
            bitField0_ = (bitField0_ & ~0x00000004);
          } else {
            ensureReceiverIsMutable();
            receiver_.addAll(other.receiver_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasContent()) {
          
          return false;
        }
        if (!hasNextplayer()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.alayse.marsserver.proto.game.Room.RoomResponseProxy parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.alayse.marsserver.proto.game.Room.RoomResponseProxy) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object content_ = "";
      /**
       * <code>required string content = 1;</code>
       */
      public boolean hasContent() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string content = 1;</code>
       */
      public java.lang.String getContent() {
        java.lang.Object ref = content_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            content_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string content = 1;</code>
       */
      public com.google.protobuf.ByteString
          getContentBytes() {
        java.lang.Object ref = content_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          content_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string content = 1;</code>
       */
      public Builder setContent(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        content_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string content = 1;</code>
       */
      public Builder clearContent() {
        bitField0_ = (bitField0_ & ~0x00000001);
        content_ = getDefaultInstance().getContent();
        onChanged();
        return this;
      }
      /**
       * <code>required string content = 1;</code>
       */
      public Builder setContentBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        content_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object nextplayer_ = "";
      /**
       * <code>required string nextplayer = 2;</code>
       */
      public boolean hasNextplayer() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string nextplayer = 2;</code>
       */
      public java.lang.String getNextplayer() {
        java.lang.Object ref = nextplayer_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            nextplayer_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string nextplayer = 2;</code>
       */
      public com.google.protobuf.ByteString
          getNextplayerBytes() {
        java.lang.Object ref = nextplayer_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          nextplayer_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string nextplayer = 2;</code>
       */
      public Builder setNextplayer(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        nextplayer_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string nextplayer = 2;</code>
       */
      public Builder clearNextplayer() {
        bitField0_ = (bitField0_ & ~0x00000002);
        nextplayer_ = getDefaultInstance().getNextplayer();
        onChanged();
        return this;
      }
      /**
       * <code>required string nextplayer = 2;</code>
       */
      public Builder setNextplayerBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        nextplayer_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.LazyStringList receiver_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureReceiverIsMutable() {
        if (!((bitField0_ & 0x00000004) == 0x00000004)) {
          receiver_ = new com.google.protobuf.LazyStringArrayList(receiver_);
          bitField0_ |= 0x00000004;
         }
      }
      /**
       * <code>repeated string receiver = 3;</code>
       */
      public com.google.protobuf.ProtocolStringList
          getReceiverList() {
        return receiver_.getUnmodifiableView();
      }
      /**
       * <code>repeated string receiver = 3;</code>
       */
      public int getReceiverCount() {
        return receiver_.size();
      }
      /**
       * <code>repeated string receiver = 3;</code>
       */
      public java.lang.String getReceiver(int index) {
        return receiver_.get(index);
      }
      /**
       * <code>repeated string receiver = 3;</code>
       */
      public com.google.protobuf.ByteString
          getReceiverBytes(int index) {
        return receiver_.getByteString(index);
      }
      /**
       * <code>repeated string receiver = 3;</code>
       */
      public Builder setReceiver(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureReceiverIsMutable();
        receiver_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string receiver = 3;</code>
       */
      public Builder addReceiver(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureReceiverIsMutable();
        receiver_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string receiver = 3;</code>
       */
      public Builder addAllReceiver(
          java.lang.Iterable<java.lang.String> values) {
        ensureReceiverIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, receiver_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string receiver = 3;</code>
       */
      public Builder clearReceiver() {
        receiver_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string receiver = 3;</code>
       */
      public Builder addReceiverBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureReceiverIsMutable();
        receiver_.add(value);
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:org.alayse.marsserver.proto.game.RoomResponseProxy)
    }

    static {
      defaultInstance = new RoomResponseProxy(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:org.alayse.marsserver.proto.game.RoomResponseProxy)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_alayse_marsserver_proto_game_RoomRequest_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_org_alayse_marsserver_proto_game_RoomRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_alayse_marsserver_proto_game_RoomResponseProxy_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_org_alayse_marsserver_proto_game_RoomResponseProxy_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\nroom.proto\022 org.alayse.marsserver.prot" +
      "o.game\"\033\n\013RoomRequest\022\014\n\004room\030\001 \002(\t\"J\n\021R" +
      "oomResponseProxy\022\017\n\007content\030\001 \002(\t\022\022\n\nnex" +
      "tplayer\030\002 \002(\t\022\020\n\010receiver\030\003 \003(\t"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_org_alayse_marsserver_proto_game_RoomRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_org_alayse_marsserver_proto_game_RoomRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_org_alayse_marsserver_proto_game_RoomRequest_descriptor,
        new java.lang.String[] { "Room", });
    internal_static_org_alayse_marsserver_proto_game_RoomResponseProxy_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_org_alayse_marsserver_proto_game_RoomResponseProxy_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_org_alayse_marsserver_proto_game_RoomResponseProxy_descriptor,
        new java.lang.String[] { "Content", "Nextplayer", "Receiver", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
